services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080

  keycloak:
    image: keycloak/keycloak
    depends_on:
      - db
    ports:
      - 8280:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL_HOST: db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: admin
    command:
      - start-dev
